### ISSUE TITLE
erros css

### ISSUE THREAD

**Issue by yurikoster1** [pixhausdigital/PixHaus_Site#6]
erro no firefox 49.0.2 no osx 10.11.6
![screen shot 2016-11-10 at 15 47 55](https://cloud.githubusercontent.com/assets/2926881/20188658/d12b9dfc-a760-11e6-92d0-5f5dd465ec12.png)

![screen shot 2016-11-10 at 15 48 05](https://cloud.githubusercontent.com/assets/2926881/20188660/d133736a-a760-11e6-9a11-677e593fd959.png)

![screen shot 2016-11-10 at 15 49 19](https://cloud.githubusercontent.com/assets/2926881/20188659/d1312790-a760-11e6-8d75-54b3c2c67486.png)

**Comment by krkoster** [comment]
ok
